services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USERNAME}", "-d", "${POSTGRES_DATABASE}" ]
      interval: 1s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      antifraud:
        condition: service_started
    volumes:
      - .:/opt/app
    env_file:
      - .env

  antifraud:
    image: lodthe/prod-backend-antifraud:latest
    environment:
      - SERVER_PORT=9090
      - CACHE_DURATION_MS=5000
    ports:
      - '9090:9090'

volumes:
  pg_data:
